server:
  port: 10086
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: orderserver #路由id，自定义，唯一即可
          uri: lb://orderserver #路由的目标地址
          predicates: #路由断言，判断 请求是否符合规则
            - Path=/order/** #按照路径匹配

        - id: userserver #路由id，自定义，唯一即可
          uri: lb://userserver #路由的目标地址
          predicates: #路由断言，判断 请求是否符合规则
            - Path=/user/** #按照路径匹配
      default-filters:
        - AddRequestHeader=mf,mf is a beautiful girl.
