server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tb_user?useSSL=false
    username: root
    password: dwysj
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: userserver
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: MF
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

ribbon:
  eager-load:
    enabled: true
    clients: userserver
