server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tb_order?useSSL=false
    username: root
    password: dwysj
    driver-class-name: com.mysql.jdbc.Driver
#  application:
#    name: orderserver
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        cluster-name: MF
#        namespace: f92654f7-7370-463a-8045-ef999a9d7d8b
#        ephemeral: false
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

userserver:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则

feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数